"""baseline: squash 54 migrations into one

全量 schema baseline：替代 2026-08-18 之前的 54 个链式迁移（历史见
git tag `pre-squash-migrations`）。

在 autogenerate（= 当前 models 真相）之上叠加两类 autogenerate 表达不了的
旧链事实：列级 server_default（按表逐列从旧链 head dump 对齐）与
content_event 规范化触发器函数/触发器（Python 侧已有等价守卫，DB 触发器
是纵深防御）。约束沿用 autogen 命名；存量库的旧命名约束结构等价，
首个后续迁移可择机统一。

- downgrade 为 no-op：squash 后不支持逐步回滚，回滚路径 = 备份恢复（backup_db.sh）。
- 存量库（alembic_version 指向旧 revision）由 run_startup_migrations 的
  兼容分支探测 schema 特征后自动 stamp 到本 baseline。


Revision ID: c003bd551911
Revises:
Create Date: 2026-08-18 19:14:05.026724

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c003bd551911"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_CANONICAL_MEMBER_GUARDS_DDL = """
CREATE FUNCTION public.enforce_content_event_canonical_member_disjoint() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
            DECLARE
                current_canonical_content_id integer;
            BEGIN
                IF TG_TABLE_NAME = 'content_event_groups' THEN
                    PERFORM 1
                    FROM content_items
                    WHERE id = NEW.canonical_content_id
                    FOR UPDATE;
                    IF EXISTS (
                        SELECT 1
                        FROM content_event_members
                        WHERE content_id = NEW.canonical_content_id
                    ) THEN
                        RAISE EXCEPTION
                            'event member cannot become canonical before member removal'
                            USING ERRCODE = '23514';
                    END IF;
                ELSE
                    PERFORM 1
                    FROM content_items
                    WHERE id = NEW.content_id
                    FOR UPDATE;
                    SELECT canonical_content_id
                    INTO current_canonical_content_id
                    FROM content_event_groups
                    WHERE canonical_content_id = NEW.content_id;
                    IF current_canonical_content_id = NEW.content_id THEN
                        RAISE EXCEPTION
                            'canonical content cannot also be an event member'
                            USING ERRCODE = '23514';
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$;
CREATE TRIGGER trg_content_event_canonical_not_member BEFORE INSERT OR UPDATE OF canonical_content_id ON public.content_event_groups FOR EACH ROW EXECUTE FUNCTION public.enforce_content_event_canonical_member_disjoint();

CREATE TRIGGER trg_content_event_member_not_canonical BEFORE INSERT OR UPDATE OF event_group_id, content_id ON public.content_event_members FOR EACH ROW EXECUTE FUNCTION public.enforce_content_event_canonical_member_disjoint();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_ids", sa.JSON(), nullable=False),
        sa.Column("skipped_inflight_ids", sa.JSON(), nullable=False),
        sa.Column("analyzed_ids", sa.JSON(), nullable=False),
        sa.Column("failed_ids", sa.JSON(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_jobs_status"), ["status"], unique=False)
        batch_op.create_index("ix_analysis_jobs_status_queued", ["status", "queued_at"], unique=False)

    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True, comment="Comma-separated keywords for fallback matching"),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_auto_created", sa.Boolean(), nullable=False, comment="True if discovered by LLM"),
        sa.Column("content_count", sa.Integer(), nullable=False, comment="Denormalized count for sorting"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "content_event_normalization_leases",
        sa.Column("scope_key", sa.String(length=80), nullable=False),
        sa.Column("fencing_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("fencing_token >= 0", name="ck_content_event_normalization_leases_fence"),
        sa.PrimaryKeyConstraint("scope_key"),
    )
    with op.batch_alter_table("content_event_normalization_leases", schema=None) as batch_op:
        batch_op.create_index("ix_content_event_normalization_leases_expiry", ["lease_expires_at"], unique=False)

    op.create_table(
        "email_verification_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_verification_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_verification_codes_email"), ["email"], unique=False)
        batch_op.create_index("ix_email_verification_email_created", ["email", "created_at"], unique=False)

    op.create_table(
        "fanqie_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.String(length=50), nullable=False),
        sa.Column("book_name", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("category_id", sa.String(length=20), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=True),
        sa.Column("thumb_uri", sa.String(length=1000), nullable=True),
        sa.Column("read_count", sa.String(length=50), nullable=True),
        sa.Column("word_number", sa.String(length=50), nullable=True),
        sa.Column("last_chapter_title", sa.String(length=500), nullable=True),
        sa.Column("last_chapter_update_time", sa.Integer(), nullable=True),
        sa.Column("current_pos", sa.Integer(), nullable=False),
        sa.Column("rank_type", sa.String(length=30), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("male_reading_pos", sa.Integer(), nullable=True),
        sa.Column("male_new_pos", sa.Integer(), nullable=True),
        sa.Column("female_reading_pos", sa.Integer(), nullable=True),
        sa.Column("female_new_pos", sa.Integer(), nullable=True),
        sa.Column("rank_pos_diff", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id"),
    )
    with op.batch_alter_table("fanqie_books", schema=None) as batch_op:
        batch_op.create_index("ix_fanqie_book_cat", ["category_id"], unique=False)
        batch_op.create_index("ix_fanqie_book_ranktype", ["rank_type"], unique=False)

    op.create_table(
        "fanqie_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fanqie_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=20), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fanqie_id"),
    )
    with op.batch_alter_table("fanqie_categories", schema=None) as batch_op:
        batch_op.create_index("ix_fanqie_cat_group", ["group"], unique=False)

    op.create_table(
        "fanqie_rank_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.String(length=10), nullable=False),
        sa.Column("book_id", sa.String(length=50), nullable=False),
        sa.Column("book_name", sa.String(length=500), nullable=False),
        sa.Column("rank_type", sa.String(length=30), nullable=False),
        sa.Column("category_id", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("read_count", sa.String(length=50), nullable=True),
        sa.Column("word_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fanqie_rank_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_snap_book", ["book_id"], unique=False)
        batch_op.create_index("ix_snap_date_type", ["snapshot_date", "rank_type"], unique=False)

    op.create_table(
        "job_execution_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_key", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="RUNNING / SUCCESS / FAILED / TIMEOUT / SKIPPED"
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True, comment="执行耗时(毫秒)"),
        sa.Column("result_summary", sa.Text(), nullable=True, comment="成功时输出摘要"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="失败时错误信息"),
        sa.Column("trigger_type", sa.String(length=20), nullable=True, comment="scheduler / manual"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_execution_logs", schema=None) as batch_op:
        batch_op.create_index("ix_job_exec_logs_job_key_started", ["job_key", "started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_execution_logs_job_key"), ["job_key"], unique=False)

    op.create_table(
        "llm_call_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("request_model", sa.String(length=200), nullable=True),
        sa.Column("actual_model", sa.String(length=200), nullable=True),
        sa.Column("scene", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=False),
        sa.Column("billable_input_tokens", sa.Integer(), nullable=False),
        sa.Column("input_cost", sa.Float(), nullable=False),
        sa.Column("output_cost", sa.Float(), nullable=False),
        sa.Column("cache_read_cost", sa.Float(), nullable=False),
        sa.Column("cache_creation_cost", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("cost_per_1m_input", sa.Float(), nullable=True),
        sa.Column("cost_per_1m_output", sa.Float(), nullable=True),
        sa.Column("cost_per_1m_input_cache_hit", sa.Float(), nullable=True),
        sa.Column("cost_per_1m_input_cache_create", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_call_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_call_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_llm_call_logs_model_created", ["model_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_call_logs_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_call_logs_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_call_logs_request_id"), ["request_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_llm_call_logs_scene"), ["scene"], unique=False)
        batch_op.create_index("ix_llm_call_logs_scene_created", ["scene", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_call_logs_status"), ["status"], unique=False)

    op.create_table(
        "llm_models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="显示名称，如 GLM-5.1"),
        sa.Column(
            "provider", sa.String(length=50), nullable=False, comment="litellm provider: openai / custom_zhipu …"
        ),
        sa.Column("model_id", sa.String(length=200), nullable=False, comment="litellm model string: openai/glm-5.1"),
        sa.Column("api_key", sa.String(length=500), nullable=True, comment="API Key (加密存储)"),
        sa.Column("api_base", sa.String(length=500), nullable=True, comment="自定义 API endpoint"),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("routing_group", sa.String(length=50), nullable=False, comment="运行时路由组"),
        sa.Column("model_family", sa.String(length=50), nullable=True, comment="模型家族，如 deepseek/qwen/glm"),
        sa.Column(
            "channel_name", sa.String(length=100), nullable=True, comment="渠道名，如 official/opencode/openrouter"
        ),
        sa.Column("routing_priority", sa.Integer(), nullable=False, comment="路由优先级，数字越小越先尝试"),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False, comment="失败后冷却秒数"),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost_per_1k_input", sa.Float(), nullable=True, comment="每1k input token 成本(元)"),
        sa.Column("cost_per_1k_output", sa.Float(), nullable=True, comment="每1k output token 成本(元)"),
        sa.Column("extra_params", sa.JSON(), nullable=True, comment="额外参数(JSON)"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_models", schema=None) as batch_op:
        batch_op.create_index("ix_llm_models_enabled", ["enabled"], unique=False)
        batch_op.create_index("ix_llm_models_route", ["routing_group", "routing_priority"], unique=False)

    op.create_table(
        "metrics_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uptime_seconds", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("http_total_requests", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("http_total_errors_5xx", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("http_error_rate", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("http_p50", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("http_p95", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("http_p99", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("http_in_progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("http_rate_limit_hits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_total_calls", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_total_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_total_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_success_rate", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("llm_total_cost_usd", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("llm_total_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_total_output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("llm_p50", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("llm_p95", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("llm_p99", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("db_pool_checked_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("db_pool_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("db_pool_utilization", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("process_rss_mb", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("process_cpu_user_s", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("process_cpu_sys_s", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("slow_queries_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metrics_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_metrics_snapshots_captured_at", ["captured_at"], unique=False)

    op.create_table(
        "model_evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("eval_run_id", sa.String(length=50), nullable=False, comment="测评批次ID"),
        sa.Column("model_id", sa.Integer(), nullable=False, comment="关联 llm_models.id"),
        sa.Column("model_name", sa.String(length=100), nullable=False, comment="快照模型名"),
        sa.Column(
            "prompt_type",
            sa.String(length=50),
            nullable=False,
            comment="测评类型: analysis/daily_report/weekly_digest/classification",
        ),
        sa.Column("prompt_text", sa.Text(), nullable=True, comment="使用的 prompt (可选存储)"),
        sa.Column("response_text", sa.Text(), nullable=True, comment="模型输出"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, comment="响应耗时(毫秒)"),
        sa.Column("tokens_input", sa.Integer(), nullable=True, comment="输入 token 数"),
        sa.Column("tokens_output", sa.Integer(), nullable=True, comment="输出 token 数"),
        sa.Column("quality_score", sa.Float(), nullable=True, comment="人工打分 1-5"),
        sa.Column("auto_score", sa.Float(), nullable=True, comment="自动评分"),
        sa.Column("notes", sa.Text(), nullable=True, comment="人工备注"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="PENDING/RUNNING/DONE/FAILED"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_evaluations", schema=None) as batch_op:
        batch_op.create_index("ix_model_evals_run_type", ["eval_run_id", "prompt_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_evaluations_eval_run_id"), ["eval_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_evaluations_model_id"), ["model_id"], unique=False)

    op.create_table(
        "monthly_digests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("month_key", sa.String(length=7), nullable=False),
        sa.Column("month_label", sa.String(length=30), nullable=False),
        sa.Column("month_start", sa.String(length=10), nullable=False),
        sa.Column("month_end", sa.String(length=10), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("takeaway", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("trends", sa.Text(), nullable=True),
        sa.Column("top_picks", sa.Text(), nullable=True),
        sa.Column("category_summary", sa.Text(), nullable=True),
        sa.Column("platform_tips", sa.Text(), nullable=True),
        sa.Column("topic_clusters", sa.Text(), nullable=True),
        sa.Column("action_items", sa.Text(), nullable=True),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("analyzed_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("category_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monthly_digests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monthly_digests_month_key"), ["month_key"], unique=True)

    op.create_table(
        "mother_topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=True),
        sa.Column("target_reader", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True, comment="NULL=系统模板；非 NULL=用户自定义 fork"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mother_topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mother_topics_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_mother_topics_owner_user_id"), ["owner_user_id"], unique=False)

    op.create_table(
        "prompt_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("scene", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), server_default=sa.text("''"), nullable=False),
        sa.Column("source_file", sa.String(length=200), server_default=sa.text("''"), nullable=False),
        sa.Column("content_preview", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("full_content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("version_hash", sa.String(length=64), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("prompt_registry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompt_registry_scene"), ["scene"], unique=False)

    op.create_table(
        "qimao_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("category1_name", sa.String(length=100), nullable=True),
        sa.Column("category2_name", sa.String(length=100), nullable=True),
        sa.Column("thumb_uri", sa.String(length=1000), nullable=True),
        sa.Column("words_num", sa.String(length=50), nullable=True),
        sa.Column("collect_count", sa.Integer(), nullable=True),
        sa.Column("latest_chapter_id", sa.String(length=50), nullable=True),
        sa.Column("latest_chapter_title", sa.String(length=500), nullable=True),
        sa.Column("update_time", sa.String(length=30), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("is_over", sa.Integer(), nullable=True),
        sa.Column("is_new", sa.Integer(), nullable=True),
        sa.Column("is_continue_top", sa.Integer(), nullable=True),
        sa.Column("index_change", sa.Integer(), nullable=True),
        sa.Column("surge_rank", sa.Integer(), nullable=True),
        sa.Column("bonus", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("rank_type", sa.String(length=20), nullable=False),
        sa.Column("date_type", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qimao_books", schema=None) as batch_op:
        batch_op.create_index("ix_qimao_book", ["book_id"], unique=False)
        batch_op.create_index("ix_qimao_channel_rank", ["channel", "rank_type"], unique=False)

    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_key", sa.String(length=100), nullable=False, comment="唯一任务标识"),
        sa.Column("name", sa.String(length=200), nullable=False, comment="显示名称"),
        sa.Column("job_type", sa.String(length=50), nullable=False, comment="cron / interval"),
        sa.Column("cron_expr", sa.String(length=100), nullable=True, comment="cron 表达式"),
        sa.Column("interval_seconds", sa.Integer(), nullable=True, comment="interval 间隔秒数"),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_key"),
    )
    with op.batch_alter_table("scheduled_jobs", schema=None) as batch_op:
        batch_op.create_index("ix_scheduled_jobs_enabled", ["enabled"], unique=False)

    op.create_table(
        "topic_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False, comment="话题名称（LLM 生成）"),
        sa.Column("keywords", sa.JSON(), nullable=True, comment="关键标签列表"),
        sa.Column("summary", sa.Text(), nullable=True, comment="话题一句话摘要"),
        sa.Column("content_count", sa.Integer(), nullable=True, comment="话题下内容数"),
        sa.Column("best_score", sa.Float(), nullable=True, comment="话题内最高精选分"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_groups", schema=None) as batch_op:
        batch_op.create_index("ix_topic_groups_best_score", [sa.text("best_score DESC")], unique=False)
        batch_op.create_index("ix_topic_groups_name", ["name"], unique=False)

    op.create_table(
        "topic_trends",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("topic_name", sa.String(length=200), nullable=True),
        sa.Column("keyword", sa.String(length=200), nullable=True),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("pick_count", sa.Integer(), nullable=False),
        sa.Column("top_items", sa.JSON(), nullable=True),
        sa.Column("calculation_version", sa.String(length=50), server_default=sa.text("'legacy-v1'"), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance_status", sa.String(length=30), server_default=sa.text("'unavailable'"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_trends", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_trends_keyword"), ["keyword"], unique=False)
        batch_op.create_index(batch_op.f("ix_topic_trends_snapshot_date"), ["snapshot_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_topic_trends_topic_id"), ["topic_id"], unique=False)

    op.create_table(
        "trending_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=13), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("hot_value", sa.Integer(), nullable=False),
        sa.Column("hot_value_raw", sa.String(length=100), nullable=False),
        sa.Column("trend", sa.String(length=20), nullable=True),
        sa.Column("cover_url", sa.String(length=1024), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("batch_id", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trending_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trending_items_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trending_items_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_trending_items_source"), ["source"], unique=False)

    op.create_table(
        "trending_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("snapshot_hour", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trending_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trending_snapshots_snapshot_date"), ["snapshot_date"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "webhook_delivery_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_key", sa.String(length=200), nullable=False, comment="去重 key"),
        sa.Column("event_type", sa.String(length=50), server_default=sa.text("'source_failure'"), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("severity", sa.String(length=20), server_default=sa.text("'warning'"), nullable=False),
        sa.Column("webhook_url_preview", sa.String(length=120), nullable=False, comment="URL 前 80 字符 + ...（脱敏）"),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("success", sa.Integer(), server_default=sa.text("0"), nullable=False, comment="0/1"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("response_preview", sa.Text(), nullable=True, comment="响应正文前 500 字符"),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_delivery_logs", schema=None) as batch_op:
        batch_op.create_index("ix_webhook_logs_alert_key", ["alert_key"], unique=False)
        batch_op.create_index("ix_webhook_logs_created", ["created_at"], unique=False)
        batch_op.create_index("ix_webhook_logs_event_type", ["event_type", "created_at"], unique=False)

    op.create_table(
        "weekly_digests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("week_key", sa.String(length=20), nullable=False),
        sa.Column("week_label", sa.String(length=50), nullable=False),
        sa.Column("week_start", sa.String(length=10), nullable=False),
        sa.Column("week_end", sa.String(length=10), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("takeaway", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("trends", sa.Text(), nullable=True),
        sa.Column("top_picks", sa.Text(), nullable=True),
        sa.Column("category_summary", sa.Text(), nullable=True),
        sa.Column("platform_tips", sa.Text(), nullable=True),
        sa.Column("topic_clusters", sa.Text(), nullable=True),
        sa.Column("action_items", sa.Text(), nullable=True),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("analyzed_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("category_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weekly_digests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_weekly_digests_week_key"), ["week_key"], unique=True)

    op.create_table(
        "zhihu_albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.String(length=50), nullable=False),
        sa.Column("sort_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("author_desc", sa.String(length=500), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("thumb_url", sa.String(length=1000), nullable=True),
        sa.Column("category1_name", sa.String(length=100), nullable=False),
        sa.Column("category2_name", sa.String(length=100), nullable=True),
        sa.Column("chapter_text", sa.String(length=100), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("original_price", sa.Integer(), nullable=False),
        sa.Column("is_exclusive", sa.Boolean(), nullable=False),
        sa.Column("is_svip", sa.Boolean(), nullable=False),
        sa.Column("is_purchased", sa.Boolean(), nullable=False),
        sa.Column("online_time", sa.Integer(), nullable=True),
        sa.Column("online_time_text", sa.String(length=100), nullable=True),
        sa.Column("tag", sa.String(length=100), nullable=True),
        sa.Column("subscription_name", sa.String(length=50), nullable=True),
        sa.Column("media_type", sa.String(length=50), nullable=True),
        sa.Column("subcategory", sa.String(length=50), nullable=True),
        sa.Column("business_line", sa.String(length=50), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rank_pos_diff", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "sort_type", name="uq_zhihu_albums_bid_sort"),
    )
    with op.batch_alter_table("zhihu_albums", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_zhihu_albums_business_id"), ["business_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_albums_category1_name"), ["category1_name"], unique=False)
        batch_op.create_index("ix_zhihu_albums_category1_sort", ["category1_name", "sort_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_albums_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_albums_position"), ["position"], unique=False)
        batch_op.create_index("ix_zhihu_albums_sort_pos", ["sort_type", "position"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_albums_sort_type"), ["sort_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_albums_title"), ["title"], unique=False)

    op.create_table(
        "zhihu_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zhihu_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(length=50), nullable=True),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("artwork", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("zhihu_categories", schema=None) as batch_op:
        batch_op.create_index("ix_zhihu_cat_parent", ["parent_id", "sort"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_categories_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_categories_zhihu_id"), ["zhihu_id"], unique=True)

    op.create_table(
        "zhihu_rank_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.String(length=100), nullable=False),
        sa.Column("sort_type", sa.String(length=50), nullable=False),
        sa.Column("category1_name", sa.String(length=100), nullable=True),
        sa.Column("category2_id", sa.String(length=50), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("zhihu_rank_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_zhihu_rank_snapshots_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_zhihu_rank_snapshots_snapshot_id"), ["snapshot_id"], unique=False)

    op.create_table(
        "content_event_normalization_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_key", sa.String(length=80), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("mode", sa.String(length=6), nullable=False),
        sa.Column("status", sa.String(length=9), server_default="running", nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=False),
        sa.Column("window_hours", sa.Integer(), nullable=False),
        sa.Column("classifier_version", sa.String(length=100), nullable=False),
        sa.Column("scanned_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("matched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pending_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("standalone_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_event_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_member_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llm_call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("predictions", sa.JSON(), nullable=True),
        sa.Column("model_routes", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("mode IN ('shadow', 'write')", name="ck_content_event_normalization_runs_mode"),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name="ck_content_event_normalization_runs_status"
        ),
        sa.CheckConstraint("fencing_token >= 1", name="ck_content_event_normalization_runs_fence"),
        sa.CheckConstraint("window_hours >= 1", name="ck_content_event_normalization_runs_window"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_key", "idempotency_key", name="uq_content_event_normalization_runs_scope_key"),
    )
    with op.batch_alter_table("content_event_normalization_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_content_event_normalization_runs_scope_started", ["scope_key", sa.text("started_at DESC")], unique=False
        )
        batch_op.create_index(
            "ix_content_event_normalization_runs_status_started", ["status", sa.text("started_at DESC")], unique=False
        )

    op.create_table(
        "daily_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True, comment="NULL=全局公共日报；非 NULL=用户专属日报"),
        sa.Column("report_date", sa.String(length=10), nullable=False),
        sa.Column("weekday", sa.String(length=10), nullable=False),
        sa.Column("edition", sa.String(length=20), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_scope", sa.String(length=20), nullable=False),
        sa.Column("source_item_ids", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("takeaway", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("trends", sa.Text(), nullable=True),
        sa.Column("top_picks", sa.Text(), nullable=True),
        sa.Column("platform_tips", sa.Text(), nullable=True),
        sa.Column("topic_count", sa.Integer(), nullable=False),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("analyzed_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "report_date", "edition", "cutoff_at", name="uq_daily_report_version"),
    )
    with op.batch_alter_table("daily_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_reports_cutoff_at"), ["cutoff_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_daily_reports_edition"), ["edition"], unique=False)
        batch_op.create_index("ix_daily_reports_owner", ["owner_user_id"], unique=False)
        batch_op.create_index("ix_daily_reports_owner_date", ["owner_user_id", "report_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_daily_reports_report_date"), ["report_date"], unique=False)

    op.create_table(
        "favorite_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=11), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("target_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("cover_url", sa.String(length=1024), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=11), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "target_type", "target_key", name="uq_favorite_user_target"),
    )
    with op.batch_alter_table("favorite_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favorite_items_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_favorite_items_user_status_created", ["user_id", "status", "created_at"], unique=False
        )
        batch_op.create_index("ix_favorite_items_user_status_position", ["user_id", "status", "position"], unique=False)
        batch_op.create_index(
            "ix_favorite_items_user_type_created", ["user_id", "target_type", "created_at"], unique=False
        )

    op.create_table(
        "issue_feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("area", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=11), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issue_feedback", schema=None) as batch_op:
        batch_op.create_index("ix_issue_feedback_severity_created", ["severity", "created_at"], unique=False)
        batch_op.create_index("ix_issue_feedback_status_created", ["status", "created_at"], unique=False)
        batch_op.create_index("ix_issue_feedback_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index("ix_notif_cat", ["category"], unique=False)
        batch_op.create_index("ix_notif_read", ["is_read"], unique=False)
        batch_op.create_index("ix_notif_target", ["target_user_id"], unique=False)

    op.create_table(
        "pick_marks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False, comment="日报日期 YYYY-MM-DD"),
        sa.Column("pick_title", sa.Text(), nullable=False, comment="选题标题（标记唯一键之一）"),
        sa.Column("action", sa.Text(), nullable=False, comment="write / watch / skip"),
        sa.Column("pick_category", sa.Text(), nullable=True),
        sa.Column("pick_source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "report_date", "pick_title", name="uq_pick_mark_user_date_title"),
    )
    with op.batch_alter_table("pick_marks", schema=None) as batch_op:
        batch_op.create_index("ix_pick_mark_action", ["user_id", "action"], unique=False)
        batch_op.create_index("ix_pick_mark_user_date", ["user_id", "report_date"], unique=False)

    op.create_table(
        "product_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=11), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=11), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_updates", schema=None) as batch_op:
        batch_op.create_index("ix_product_updates_shipped_at", ["shipped_at"], unique=False)
        batch_op.create_index("ix_product_updates_status_created", ["status", "created_at"], unique=False)
        batch_op.create_index("ix_product_updates_version", ["version"], unique=False)

    op.create_table(
        "read_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=14), nullable=False),
        sa.Column("target_key", sa.String(length=64), nullable=False, comment="report_date / week_key / month_key"),
        sa.Column("target_id", sa.Integer(), nullable=True, comment="对应 ORM 主键，便于关联查询"),
        sa.Column("read_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("accumulated_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "max_progress",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="最高阅读完成度 0-100（预留，第一版不填）",
        ),
        sa.Column("depth", sa.String(length=9), server_default=sa.text("'read'"), nullable=False),
        sa.Column("topic_keywords", sa.JSON(), nullable=True, comment="报告关键词快照数组"),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("first_read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "target_type", "target_key", name="uq_read_record_user_target"),
    )
    with op.batch_alter_table("read_records", schema=None) as batch_op:
        batch_op.create_index("ix_read_record_user_last_read", ["user_id", "last_read_at"], unique=False)
        batch_op.create_index(
            "ix_read_record_user_type_last_read", ["user_id", "target_type", "last_read_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_read_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.String(length=20), server_default=sa.text("'system'"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("keyword", sa.Text(), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetch_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("last_modified", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False, comment="True=系统自动创建的信源，对用户不可见且不计入配额"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index("ix_sources_owner", ["owner_user_id"], unique=False)
        batch_op.create_index("ix_sources_owner_enabled", ["owner_user_id", "enabled"], unique=False)

    op.create_table(
        "user_api_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="用户可读的名字，如 'CI 脚本'"),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_api_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_user_api_tokens_token_active", ["token_hash", "revoked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_api_tokens_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index("ix_user_api_tokens_user_active", ["user_id", "revoked_at"], unique=False)

    op.create_table(
        "user_integrations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.String(length=20), nullable=True),
        sa.Column("last_sync_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_integrations_user_provider"),
    )
    with op.batch_alter_table("user_integrations", schema=None) as batch_op:
        batch_op.create_index("ix_user_integrations_user_provider", ["user_id", "provider"], unique=False)

    op.create_table(
        "user_interest_vectors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("signal_source", sa.String(length=30), server_default=sa.text("'manual'"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tag", name="uq_user_interest_tag"),
    )
    with op.batch_alter_table("user_interest_vectors", schema=None) as batch_op:
        batch_op.create_index("ix_user_interest_vectors_user", ["user_id"], unique=False)
        batch_op.create_index("ix_user_interest_vectors_user_weight", ["user_id", "weight"], unique=False)

    op.create_table(
        "user_oauth_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_user_oauth_accounts_provider_user"),
    )
    with op.batch_alter_table("user_oauth_accounts", schema=None) as batch_op:
        batch_op.create_index("ix_user_oauth_accounts_provider_email", ["provider", "provider_email"], unique=False)
        batch_op.create_index("ix_user_oauth_accounts_user_id", ["user_id"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_user_sessions_token_active", ["token_hash", "revoked_at"], unique=False)
        batch_op.create_index("ix_user_sessions_user_expires", ["user_id", "expires_at"], unique=False)

    op.create_table(
        "weread_stats_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cache_type", sa.String(length=20), nullable=False),
        sa.Column("read_type", sa.String(length=10), server_default=sa.text("'all'"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "cache_type", "read_type", name="uq_weread_cache_user_type_period"),
    )
    with op.batch_alter_table("weread_stats_cache", schema=None) as batch_op:
        batch_op.create_index("ix_weread_cache_user_type", ["user_id", "cache_type"], unique=False)

    op.create_table(
        "content_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("owner_user_id", sa.Integer(), nullable=True, comment="冗余 source.owner_user_id；NULL=公共内容池"),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.String(length=1024), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=9), nullable=False),
        sa.Column("is_favorited", sa.Boolean(), nullable=False),
        sa.Column("skip_analysis", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("skip_reason", sa.String(length=200), nullable=True),
        sa.Column("analysis_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("analysis_next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis_claim_token", sa.String(length=64), nullable=True),
        sa.Column("analysis_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic_groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "content_hash", name="uq_content_items_source_hash"),
    )
    with op.batch_alter_table("content_items", schema=None) as batch_op:
        batch_op.create_index("ix_content_items_crawled_at", [sa.text("crawled_at DESC")], unique=False)
        batch_op.create_index("ix_content_items_owner", ["owner_user_id"], unique=False)
        batch_op.create_index("ix_content_items_owner_status", ["owner_user_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_content_items_skip_analysis"), ["skip_analysis"], unique=False)
        batch_op.create_index("ix_content_items_source_id", ["source_id"], unique=False)
        batch_op.create_index("ix_content_items_status_crawled", ["status", sa.text("crawled_at DESC")], unique=False)
        batch_op.create_index("ix_content_items_topic_id", ["topic_id"], unique=False)

    op.create_table(
        "notification_reads",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "notification_id"),
    )
    with op.batch_alter_table("notification_reads", schema=None) as batch_op:
        batch_op.create_index("ix_notification_reads_user", ["user_id"], unique=False)

    op.create_table(
        "source_evidence_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("publisher_identity", sa.String(length=100), nullable=False),
        sa.Column("publisher_family", sa.String(length=100), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("publisher_kind", sa.String(length=30), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("official_domains", sa.JSON(), nullable=True),
        sa.Column("verification_proof_url", sa.String(length=1024), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("managed_by_admin", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", name="uq_evidence_profile_source"),
    )
    with op.batch_alter_table("source_evidence_profiles", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_profile_identity", ["publisher_identity"], unique=False)

    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("hot_score", sa.Float(), nullable=True),
        sa.Column("freshness_score", sa.Float(), nullable=True),
        sa.Column("creator_score", sa.Float(), nullable=True),
        sa.Column("viral_score", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("platform_fit", sa.JSON(), nullable=True),
        sa.Column("recommended_reason", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("key_points", sa.JSON(), nullable=True),
        sa.Column("audience_emotion", sa.Text(), nullable=True),
        sa.Column("creator_angles", sa.JSON(), nullable=True),
        sa.Column("title_suggestions", sa.JSON(), nullable=True),
        sa.Column("outline_suggestions", sa.JSON(), nullable=True),
        sa.Column("xiaohongshu_plan", sa.JSON(), nullable=True),
        sa.Column("short_video_plan", sa.JSON(), nullable=True),
        sa.Column("risk_notes", sa.JSON(), nullable=True),
        sa.Column("curation_score", sa.Float(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("source_weight", sa.Float(), nullable=True),
        sa.Column("info_density", sa.Float(), nullable=True),
        sa.Column("actionability", sa.Float(), nullable=True),
        sa.Column("analysis_mode", sa.Text(), nullable=True),
        sa.Column("prescreen_model", sa.Text(), nullable=True),
        sa.Column("final_model", sa.Text(), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("prescreen_confidence", sa.Float(), nullable=True),
        sa.Column("prescreen_score", sa.Float(), nullable=True),
        sa.Column("enrichment_status", sa.Text(), nullable=True),
        sa.Column("enrichment", sa.JSON(), nullable=True),
        sa.Column("summary_source", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ai_analyses_content_created",
            ["content_id", sa.text("created_at DESC"), sa.text("id DESC")],
            unique=False,
        )

    op.create_table(
        "article_reader_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("extraction_method", sa.String(length=24), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("article_reader_events", schema=None) as batch_op:
        batch_op.create_index("ix_article_reader_events_content_created", ["content_id", "created_at"], unique=False)
        batch_op.create_index("ix_article_reader_events_outcome_created", ["outcome", "created_at"], unique=False)

    op.create_table(
        "article_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("canonical_url", sa.String(length=1024), nullable=False),
        sa.Column("fetch_status", sa.String(length=24), server_default=sa.text("'ready'"), nullable=False),
        sa.Column("extraction_method", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("byline", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("content_blocks", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text_content_zh", sa.Text(), nullable=True),
        sa.Column("content_blocks_zh", sa.JSON(), nullable=True),
        sa.Column("reading_minutes", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id"),
    )
    with op.batch_alter_table("article_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_article_snapshots_expires_at", ["expires_at"], unique=False)
        batch_op.create_index("ix_article_snapshots_fetch_status", ["fetch_status"], unique=False)

    op.create_table(
        "content_event_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("canonical_content_id", sa.Integer(), nullable=False),
        sa.Column("canonical_policy", sa.String(length=30), server_default="earliest", nullable=False),
        sa.Column("canonical_reason", sa.Text(), nullable=True),
        sa.Column("canonical_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("canonical_locked_by_user_id", sa.Integer(), nullable=True),
        sa.Column("canonical_locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_occurrence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_occurrence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=8), server_default="active", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("classifier_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "canonical_policy IN ('earliest', 'manual')", name="ck_content_event_groups_canonical_policy"
        ),
        sa.CheckConstraint("status IN ('shadow', 'active', 'archived')", name="ck_content_event_groups_status"),
        sa.CheckConstraint(
            "first_occurrence_at <= last_occurrence_at", name="ck_content_event_groups_occurrence_order"
        ),
        sa.CheckConstraint("version >= 1", name="ck_content_event_groups_version"),
        sa.ForeignKeyConstraint(["canonical_content_id"], ["content_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["canonical_locked_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_content_id", name="uq_content_event_groups_canonical_content"),
    )
    with op.batch_alter_table("content_event_groups", schema=None) as batch_op:
        batch_op.create_index("ix_content_event_groups_locked", ["canonical_locked"], unique=False)
        batch_op.create_index(
            "ix_content_event_groups_owner_last", ["owner_user_id", sa.text("last_occurrence_at DESC")], unique=False
        )

    op.create_table(
        "content_evidence_marks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("cross_source_level", sa.String(length=30), server_default=sa.text("'none'"), nullable=False),
        sa.Column("platform_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("platforms", sa.JSON(), nullable=True),
        sa.Column("has_primary_source", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("has_official_source", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("evidence_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("independent_publisher_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", "owner_user_id", name="uq_evidence_marks_scope"),
    )
    with op.batch_alter_table("content_evidence_marks", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_marks_content", ["content_id"], unique=False)
        batch_op.create_index("ix_evidence_marks_owner", ["owner_user_id"], unique=False)
        batch_op.create_index(
            "uq_evidence_marks_public_content",
            ["content_id"],
            unique=True,
            sqlite_where=sa.text("owner_user_id IS NULL"),
            postgresql_where=sa.text("owner_user_id IS NULL"),
        )

    op.create_table(
        "content_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("favorites", sa.Integer(), nullable=True),
        sa.Column("followers_count", sa.Integer(), nullable=True),
        sa.Column("engagement_rate", sa.Float(), nullable=True),
        sa.Column("explosion_ratio", sa.Float(), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_metrics", schema=None) as batch_op:
        batch_op.create_index("ix_content_metrics_content_id", ["content_id"], unique=False)

    op.create_table(
        "content_relations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), server_default=sa.text("'0.5'"), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id", "relation_type", name="uq_content_relations_triple"),
    )
    with op.batch_alter_table("content_relations", schema=None) as batch_op:
        batch_op.create_index("ix_content_relations_source", ["source_id"], unique=False)
        batch_op.create_index("ix_content_relations_target", ["target_id"], unique=False)
        batch_op.create_index("ix_content_relations_type", ["relation_type"], unique=False)

    op.create_table(
        "creation_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_name", sa.String(length=100), nullable=True),
        sa.Column("content_title_snapshot", sa.String(length=500), nullable=True, comment="内容删除后仍能展示历史方案"),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creation_plans", schema=None) as batch_op:
        batch_op.create_index("ix_creation_plans_content", ["content_id"], unique=False)
        batch_op.create_index("ix_creation_plans_user", ["user_id"], unique=False)
        batch_op.create_index("ix_creation_plans_user_platform", ["user_id", "platform"], unique=False)

    op.create_table(
        "evidence_interactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("interaction_type", sa.String(length=30), nullable=False),
        sa.Column("cross_source_level", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_interactions", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_interactions_content", ["content_id"], unique=False)
        batch_op.create_index("ix_evidence_interactions_type", ["interaction_type"], unique=False)

    op.create_table(
        "ignored_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", name="uq_ignored_content"),
    )
    op.create_table(
        "topic_trend_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trend_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("selected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("title_snapshot", sa.String(length=500), nullable=False),
        sa.Column("url_snapshot", sa.String(length=1024), nullable=False),
        sa.Column("source_id_snapshot", sa.Integer(), nullable=True),
        sa.Column("source_name_snapshot", sa.String(length=255), nullable=True),
        sa.Column("source_type_snapshot", sa.String(length=50), nullable=True),
        sa.Column("platform_snapshot", sa.String(length=100), nullable=True),
        sa.Column("published_at_snapshot", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawled_at_snapshot", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_basis", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trend_id"], ["topic_trends.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trend_id", "content_id", name="uq_topic_trend_member_content"),
    )
    with op.batch_alter_table("topic_trend_members", schema=None) as batch_op:
        batch_op.create_index("ix_topic_trend_members_content_id", ["content_id"], unique=False)
        batch_op.create_index("ix_topic_trend_members_trend_position", ["trend_id", "position"], unique=False)

    op.create_table(
        "user_feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("feedback_type", sa.String(length=12), nullable=False),
        sa.Column("score_delta", sa.Float(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", "user_id", name="uq_user_feedback_content_user"),
    )
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.create_index("ix_user_feedback_content_user", ["content_id", "user_id"], unique=False)
        batch_op.create_index("ix_user_feedback_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "content_event_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_group_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=13), server_default="duplicate", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=False),
        sa.Column("detector_version", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=9), server_default="pending", nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('duplicate', 'corroboration', 'update')", name="ck_content_event_members_relation_type"
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'auto', 'confirmed', 'rejected')",
            name="ck_content_event_members_review_status",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_content_event_members_confidence"),
        sa.ForeignKeyConstraint(["content_id"], ["content_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_group_id"], ["content_event_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", name="uq_content_event_members_content"),
        sa.UniqueConstraint("event_group_id", "content_id", name="uq_content_event_members_group_content"),
    )
    with op.batch_alter_table("content_event_members", schema=None) as batch_op:
        batch_op.create_index(
            "ix_content_event_members_group_relation_matched",
            ["event_group_id", "relation_type", "matched_at"],
            unique=False,
        )

    op.create_table(
        "content_evidence_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mark_id", sa.Integer(), nullable=False),
        sa.Column("evidence_content_id", sa.Integer(), nullable=True),
        sa.Column("evidence_url", sa.String(length=1024), nullable=True),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("publisher_family", sa.String(length=100), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("time_delta_minutes", sa.Float(), nullable=True),
        sa.Column("match_basis", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["evidence_content_id"], ["content_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["mark_id"], ["content_evidence_marks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_evidence_links", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_links_mark", ["mark_id"], unique=False)

    # ### end Alembic commands ###

    # content_event 规范化守卫（旧链 20260729_1100 引入，autogenerate 不感知）
    op.execute(_CANONICAL_MEMBER_GUARDS_DDL)


def downgrade() -> None:
    """no-op：squash 后不支持逐步回滚，回滚路径为备份恢复（backup_db.sh）。"""
